version: '3'

services:
  boarddb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306

  spring-boot-start-real:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: real
    image: kboy1025/spring-boot-start:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - boarddb

  spring-boot-start-dev:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
    image: kboy1025/spring-boot-start:0.0.1
    ports:
      - "8081:8081"
    depends_on:
      - boarddb