version: '3'

services:
  board-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin

  spring-boot-start:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      -
    image: openjdk:11
    command: "java -jar /usr/src/myapp/spring-boot-start-0.0.1-SNAPSHOT.jar"
    ports:
      - "8081:8080"
    volumes:
    - ~/docker/spring-boot-start/app:/usr/src/myapp